const OrderData = [
  {
    "phone_number": "663-4523",
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "673-4333",
    "order_number": "3346",
    "drinks": "",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
    "status_food": "2",
    "status_drink": "2",
    "status_pay": "0",
  },
  {
    "phone_number": "863-2223",
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "9",
    "status_food": "3",
    "status_drink": "3",
    "status_pay": "1",
  },
  {
    "phone_number": "633-5523",
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "664-4444",
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "553-5623",
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
    "status_food": "1",
    "status_drink": "3",
    "status_pay": "0",
  },
  {
    "phone_number": "773-7777",
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
    "status_food": "1",
    "status_drink": "2",
    "status_pay": "0",
  },
  {
    "phone_number": "655-5553",
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "13",
    "status_food": "3",
    "status_drink": "3",
    "status_pay": "0",
  },
  {
    "phone_number": "669-9999",
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
    "status_food": "2",
    "status_drink": "3",
    "status_pay": "0",
  },
  {
    "phone_number": "668-8888",
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "11",
    "status_food": "2",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "665-5555",
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "777-4000",
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "823-2323",
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "9",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "663-4523",
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
    "status_food": "3",
    "status_drink": "3",
    "status_pay": "1",
  },
  {
    "phone_number": "868-8686",
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
    "status_food": "3",
    "status_drink": "3",
    "status_pay": "1",
  },
  {
    "phone_number": "663-2626",
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "5",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  },
  {
    "phone_number": "873-8888",
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
    "status_food": "2",
    "status_drink": "3",
    "status_pay": "0",
  },
  {
    "phone_number": "853-3456",
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
    "status_food": "1",
    "status_drink": "1",
    "status_pay": "0",
  }
]

export default OrderData;
