const OrderData = [
  {
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
  },
  {
    "order_number": "3346",
    "drinks": "",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
  },
  {
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
  },
  {
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
  },
  {
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
  },
  {
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
  },
  {
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
  },
  {
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
  },
  {
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
  },
  {
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
  },
  {
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
  },
  {
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
  },
  {
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
  },
  {
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
  },
  {
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
  },
  {
    "order_number": "3345",
    "drinks": "2x Boli 0,5L - Viking Classic 0,5L",
    "food":"",
    "price": "3290kr",
    "table_number": "12",
  },
  {
    "order_number": "3346",
    "drinks": "Viking Classic 0,5L",
    "food": "Franskar Stór",
    "price": "3290kr",
    "table_number": "4",
  },
  {
    "order_number": "3347",
    "drinks": "3x Gull 0,5L",
    "food": "Beikonborgari",
    "price": "3290kr",
    "table_number": "6",
  }
]

export default OrderData;
